[package]
name = "play_sudoku"
version = "0.1.0"
authors = ["David Wang <millimillenary@gmail.com>"]

[dependencies]
sdl2 = "*"

[dependencies.sdl2_image]
git = "https://github.com/xsleonard/rust-sdl2_image"
